//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace teknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblArizaDetay
    {
        public int ArızaId { get; set; }
        public Nullable<int> İslem { get; set; }
        public string Sorun { get; set; }
        public string Aciklama { get; set; }
        public Nullable<decimal> Onfiyat { get; set; }
        public Nullable<decimal> NetFiyat { get; set; }
        public string Islemler { get; set; }
    }
}
